server:
  host: "0.0.0.0"
  port: 3000

database:
  host: "localhost"
  port: "27017"
  dbname: "PPM"
  username: ""
  password: ""

jwt:
  secret: "this_is_my_secret"
  expiry: 10
  refresh_expiry: 60
